# Generated by Django 4.1.3 on 2022-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biotext',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
