# Generated by Django 4.1.3 on 2022-11-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_tag', models.CharField(choices=[('US', 'User'), ('MA', 'Maker'), ('FI', 'Fixer'), ('TE', 'Teacher'), ('HE', 'Helper')], default='US', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(related_name='user_list', to='myapp.skill'),
        ),
    ]
