# Generated by Django 4.1.3 on 2022-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customuser_skills_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.ManyToManyField(related_name='user_list', to='myapp.skill'),
        ),
    ]
