# Generated by Django 4.1.3 on 2022-12-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_list', to='myapp.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_tag',
            field=models.CharField(default='User', max_length=10),
        ),
    ]
