# Generated by Django 4.1.3 on 2022-12-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_customuser_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='posts',
        ),
    ]
