# Generated by Django 4.1.3 on 2022-12-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_comment_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exTag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_list', to='myapp.exchange'),
        ),
    ]
