# Generated by Django 4.1.3 on 2022-12-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_post_extag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
